<?
require_once("_common/content/MarkupCode.php");
require_once("_common/content/CustomCode.php");
require_once("_common/content/Tag.php");
require_once("_common/content/Page.php");
require_once("_common/content/xhtmlmp/XHTMLMPPage.php");
/*require_once("_common/content/html/Title.php");
require_once("_common/content/html/CSS.php");
require_once("_common/content/html/Meta.php");
require_once("_common/content/html/Charset.php");*/
?>